name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Descargar APK
        run: |
          wget -O app.apk "URL_DEL_APK"  # O usa el APK de tu repo

      - name: Descompilar APK
        run: |
          sudo apt update && sudo apt install -y jadx
          jadx -d apk_source app.apk

      - name: Configurar SonarCloud
        run: |
          echo "sonar.projectKey=TU_PROYECTO" > sonar-project.properties
          echo "sonar.organization=TU_ORGANIZACION" >> sonar-project.properties
          echo "sonar.sources=apk_source" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties

      - name: Ejecutar SonarScanner
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
